sudo: required
language: bash
services: docker
before_install:
  - cd /
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push magsond/mysql-rest-with;
    docker push magsond/rest-with-spring-boot;
  on:
    branch: master
notifications:
  email: false
