version: '3.4'
services:
  db:
    image: magsond/mysql-rest-with
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with
    ports:
      - "3308:3306"
    networks:
      - md-network
  rest-with-spring-boot:
    image: magsond/rest-with-spring-boot
    restart: always
    build: ./RestWith
    working_dir: /RestWith
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./RestWith:/RestWith
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - md-network
networks:
    md-network:
        driver: bridge